### ISSUE TITLE
Game Crashes when viewing Tile Entities

### ISSUE THREAD

**Issue by KxttyKxt** [Snownee/Jade#319] opened 2023-10-15 21:47 UTC
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.3.0

### Modloader version

Forge 40.2.10

### Modpack info

https://www.curseforge.com/minecraft/modpacks/lucrative

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/KxttyKxt/7daf28a37939f5a20e5a720dfeefbc22

### Issue description

I played with the tooltip disabled up until the very last point when the game crashed.
I was looking at a crafting table from the Visual Workbench mod. The moment I enabled the Jade Tooltip by pressing NUMPAD 1, the game crashed. [Here](https://gist.github.com/KxttyKxt/12c832544ea1ff78a73eda8c8b9da6a4) is the crash log, with the header, `Unexpected Error: java.lang.NullPointerException: Cannot read field "f_82470_" because "translate" is null`. All suspected tile entities produce this same crash when looking directly at them (so that Jade attempts to render them in a tooltip).

This issue did not used to happen. It started happening a few days ago. Since then, the issue has also occurred with chests, armor stands, and beds, but not always for those three.

I suspect it is an issue with the [Faithless resource pack](https://www.curseforge.com/minecraft/texture-packs/faithless/files/4332556) I have enabled in this modpack. 

There is a mod that--when combined with this resource pack--allows special entity and tile entity and block rendering; this mod is [[EMF] Entity Model Features](https://www.curseforge.com/minecraft/mc-mods/entity-model-features/files/4780256). However, this issue persists even after I disabled EMF.

**Comment by Snownee** [comment] 2023-10-15 23:06
Please do not use Saturn for the time being. It is causing the crash.

**Comment by Snownee** [comment] 2023-10-15 23:07
Duplicate of #316

**Closed as not planned by Snownee** 2023-10-15 23:07 UTC
