### ISSUE TITLE
Game crashes with Tinkers and Saturn with Unexpected Error

### ISSUE THREAD

**Issue by Alv-Rod** [Snownee/Jade#318] opened 2023-10-15 17:58 UTC
### Mod loader

Forge

### Minecraft version

1.18.2

### Mod version

5.3.0

### Modloader version

Forge: 40.2.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/Alv-Rod/2f51e913c22d20c4880293cd083a0f91

### Issue description

When playing with Jade, Tinkers Construct (and Mantle) and Saturn, if i place a crafting station (crafting table that keeps and shows items on it), place an item on it, and then look at the table, the game crashes with Unexpected Error, and Jade seems to be the problem.

**Comment by Snownee** [comment] 2023-10-15 23:06
Please do not use Saturn for the time being. It is causing the crash.

**Comment by Snownee** [comment] 2023-10-15 23:07
Duplicate of #316

**Closed as not planned by Snownee** 2023-10-15 23:07 UTC
