### ISSUE TITLE
a panda idea

### ISSUE THREAD

**Issue by QingSu6** [Snownee/Jade#450] opened 2024-08-07 11:51 UTC
### Mod loader

Fabric

### Minecraft version

1.20.4

### Mod version

13.3.1

### Modloader version

Fabric:Loader 0.15.11 + API 0.97.1

### [IMPORTANT] If bug:

- [ ] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

I got a suggestion,why can't we display the panda's genes like we display the horse's state
![微信截图_20240807194522](https://github.com/user-attachments/assets/7d39d09f-caf8-42cc-8aea-c4fe1f819082)
![微信截图_20240807194534](https://github.com/user-attachments/assets/6d9f58bb-a1ee-44ba-998c-86ff5578b847)

**Comment by Snownee** [comment] 2024-08-14 11:11
Duplicate of #397

**Closed as not planned by Snownee** 2024-08-14 11:11 UTC

**Comment by Snownee** [comment] 2024-08-23 18:10
for those who want this feature, I've made a KubeJS plugin for it: https://github.com/Snownee/Jade/issues/397#issuecomment-2307574365
