### ISSUE TITLE
[SUGGESTION] Optional Item Dependency

### ISSUE THREAD

**Issue by BookerCatch** [Snownee/Jade#209] opened 2023-01-31 20:03 UTC
### Mod loader

Forge

### Minecraft version

1.19.2

### Mod version

8.7.0

### Modloader version

Forge: 43.2.4

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

If not too much trouble, it would be nice to have an option making it so the HUD element renders only when the player has a user-defined item(s) (via datapacks or config) in the inventory/held/hotbar/equipped. 

I am aware The One Probe accomplishes this request, but I think allowing the player to define specific items allows greater freedom for modpack design and enhancing the utility brought upon by certain items. For instance, consider a special "Orb of Clairvoyance," or an advanced visor worn in tech packs. Or a probe. Ha. I prefer this mod, however; thus the request.

**Comment by Snownee** [comment] 2023-01-31 20:04
Duplicate of https://github.com/Snownee/JadeAddons/issues/15

**Closed as completed by Snownee** 2023-01-31 20:04 UTC
