### ISSUE TITLE
Suspicious blocks labeled as their normal variants

### ISSUE THREAD

**Issue by milkev** [Snownee/Jade#277] opened 2023-07-23 02:14 UTC
### Mod loader

Fabric

### Minecraft version

1.20.1

### Mod version

11.3.0

### Modloader version

Loader0.14.21, api 0.85.0

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### Issue description

When you look at a suspicious block (the new archeology variants of gravel & a few other blocks) jade just says its the regular block.

**Comment by Snownee** [comment] 2023-07-23 02:21
Duplicate of #250

**Closed as not planned by Snownee** 2023-07-23 02:21 UTC

**Comment by milkev** [comment] 2023-07-23 02:41
strange, it didnt show up when i searched the github, my bad.

**Comment by bernzrdo** [comment] 2023-07-23 09:41
@milkev GitHub automatically filters closed issues.

**Comment by milkev** [comment] 2023-07-23 17:46
> @milkev GitHub automatically filters closed issues.

yeah, i searched closed issues too, maybe i misspelled suspicious. oh well. this is why we have 'mark as duplicate'
