### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by MuteTiefling** [Snownee/Jade#374] opened 2024-02-13 11:25 UTC
### Mod loader

NeoForge

### Minecraft version

1.20.4

### Mod version

Jade-1.20.4-neoforge-13.2.2

### Modloader version

Neoforge - 20.4.157

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://gist.github.com/MuteTiefling/ba3cee0a983a2b500897af26b5254502

### Issue description

Game won't load with Jade installed. Just crashes on startup.

**Comment by Snownee** [comment] 2024-02-13 11:30
Duplicate of #360

**Closed as not planned by Snownee** 2024-02-13 11:30 UTC
