### ISSUE TITLE
1.20.1forge渲染错误

### ISSUE THREAD

**Issue by wsxiya** [Snownee/Jade#301] opened 2023-09-08 10:09 UTC
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

11.5.1

### Modloader version

forge47.1.3

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

当调整显示缩放，不=1时，挖掘进度条显示的位置不对
![J{}4 ~3$_UAX2)%9TFDLK$0](https://github.com/Snownee/Jade/assets/114494454/a5480fc4-169c-43d7-8399-b9e611c24b2b)

**Comment by Snownee** [comment] 2023-09-08 10:51
Duplicate of #295

**Closed as not planned by Snownee** 2023-09-08 10:51 UTC
