### ISSUE TITLE
Bug in tooltip with minecraft transit railway

### ISSUE THREAD

**Issue by xhaooy** [Snownee/Jade#229] opened 2023-04-10 20:53 UTC
### Mod loader

Fabric

### Minecraft version

1.19.2

### Mod version

8.7.3, jade addons: 3.1.0

### Modloader version

fabric: 0.14.19, fabric-api-0.76.0+1.19.2

### Modpack info

just mine

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

nothing in logs

### Issue description

Sometimes jade shows blank tooltip with mod name: Minecraft Transit Railway. when in bed, looking at nothing(air), or even block(after moving cursor a bit it will show correct block, might bug again)

downloaded from: https://www.curseforge.com/minecraft/mc-mods/minecraft-transit-railway
version: MTR-fabric-1.19.2-3.2.0

**Comment by Snownee** [comment] 2023-04-11 16:51
Duplicate of #177

**Closed as completed by Snownee** 2023-04-11 16:51 UTC
