### ISSUE TITLE
gamecrash after new mod update

### ISSUE THREAD

**Issue by Skeetle** [Snownee/Jade#47] opened 2021-05-10 15:14 UTC
Hey there,
after the latest update my Minecraft keeps crashing when I look around in my world I get following error code:

Error: java.lang.NullPointerException: TooltipRenderer jade:sub doesn't exist

Thanks.

**Comment by Snownee** [comment] 2021-05-10 15:31
Duplicate of #45

**Closed as completed by Snownee** 2021-05-10 15:31 UTC
