### ISSUE TITLE
实体生命与资源包存在BUG

### ISSUE THREAD

**Issue by CCC-9527** [Snownee/Jade#234] opened 2023-04-19 02:09 UTC
### Mod loader

Fabric

### Minecraft version

1.19.4

### Mod version

10.0.0

### Modloader version

fabric 0.78.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

![2023-04-11_19 31 07](https://user-images.githubusercontent.com/129697452/232948256-6cac427f-55bc-4fee-a60f-d9bf1d427e61.png)

**Comment by CCC-9527** [comment] 2023-04-19 02:13
[https://wwfx.lanzouw.com/i1w2d0te8gcf](url)

资源包链接

**Comment by Snownee** [comment] 2023-04-19 06:49
没看懂

**Comment by CCC-9527** [comment] 2023-04-20 11:26
> 没看懂

就是安装玉之后，鼠标指向一个有职业的村民，会有bug(和资源包同时使用)

**Comment by Snownee** [comment] 2023-04-22 18:44
Duplicate of #235

**Closed as not planned by Snownee** 2023-04-22 18:44 UTC
