### ISSUE TITLE
El Juego se cierra al abrir cualquier mundo viejo o nuevo

### ISSUE THREAD

**Issue by d-rick** [Snownee/Jade#44] opened 2021-05-05 01:21 UTC
* Forge Version: 35.1.37 para minecraft 1.16.4
 * Mod Version: Jade-1.16.4-2.7.0

drop crash report here if you have
[crash-2021-05-04_20.15.06-client.txt](https://github.com/Snownee/Jade/files/6424664/crash-2021-05-04_20.15.06-client.txt)

**Comment by Snownee** [comment] 2021-05-05 04:12
无法复现

**Comment by Snownee** [comment] 2021-05-08 20:33
Duplicate of #45

**Closed as completed by Snownee** 2021-05-08 20:33 UTC
