### ISSUE TITLE
counting error, 10.3k

### ISSUE THREAD

**Issue by denny4-user** [Snownee/Jade#444] opened 2024-07-31 06:22 UTC
### Mod loader

Please select

### Minecraft version

1.19.2

### Mod version

8.9.1

### Modloader version

Forge 43.3.5

### [IMPORTANT] If bug:

- [X] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### Issue description

For some reason, with the "create" mod - the mod does not display the number of items in the storage correctly, how can I fix this?

(in the photo there is 10.3k of sand - in fact there is 3 times more if you get everything)
![image](https://github.com/user-attachments/assets/691fffcc-6d96-4968-8932-9b9077d2bdc3)

**Comment by Snownee** [comment] 2024-07-31 06:30
Duplicate of #328

**Closed as not planned by Snownee** 2024-07-31 06:30 UTC
